# For full config options, check the docs:
#    docs.serverless.com
service: newspaper-api
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-s3-local

provider:
  name: aws
  runtime: nodejs16.x
  stage:  ${file(./env.${opt:stage}.yml):stage}
  region:  ${file(./env.${opt:stage}.yml):deployRegion}
  timeout: 120

custom:
  apiGatewayCaching:
    enabled: true
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node16'
    define: { 'require.resolve': undefined }
    platform: 'node'
  output:
    file: .serverless/output.json
  s3:
    host: localhost
    directory: ./S3

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local

functions:
  - ${file(./src/endpoints/offers/serverless.yml)}
  - ${file(./src/endpoints/types/serverless.yml)}
  - ${file(./src/endpoints/names/serverless.yml)}
  - ${file(./src/endpoints/durations/serverless.yml)}
  - ${file(./src/endpoints/saveOffers/serverless.yml)}