# For full config options, check the docs:
#    docs.serverless.com
service: provider-api
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage:  ${file(./env.${opt:stage}.yml):stage}
  region:  ${file(./env.${opt:stage}.yml):deployRegion}
  timeout: 120

custom:
  serverless-offline:
    httpPort: 5000
    lambdaPort: 3003
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node16'
    define: { 'require.resolve': undefined }
    platform: 'node'
  output:
    file: .serverless/output.json


functions:
  - ${file(./src/endpoints/offers/serverless.yml)}
  - ${file(./src/endpoints/newspapers/serverless.yml)}