healthcheck:
  handler: src/endpoints/offers/functions/findOffers/index.handler
  description: Find all offers from provider
  events:
    - http:
        path: newspapers/offers
        method: get
        cors: true
  tags:
    version: ${file(./env.${opt:stage, self:provider.stage}.yml):version}
    env: ${opt:stage}
    service: newspaper-api