findNames:
  handler: src/endpoints/names/functions/findNames/index.handler
  description: Find all names from provider
  events:
    - http:
        path: names
        method: get
        cors: true
  tags:
    version: ${file(./env.${opt:stage, self:provider.stage}.yml):version}
    env: ${opt:stage}
    service: newspaper-api